<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>visualization_tools</name>
  <version>1.0.0</version>
  <description> RViz panels for drt_behavior by Dexterous Robotics Team of JSC </description>
  <maintainer email="misha.savchenko@nasa.gov">Misha Savchenko</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- RVIZ -->
  <build_depend>qtbase5-dev</build_depend>

  <!-- ROS Public Dependencies  -->
  <depend>rclcpp</depend>
  <depend>rviz_common</depend>
  <depend>btcpp_ros2_interfaces</depend>

  <!-- QT Dependencies -->
  <exec_depend>libqt5-core</exec_depend>
  <exec_depend>libqt5-gui</exec_depend>
  <exec_depend>libqt5-opengl</exec_depend>
  <exec_depend>libqt5-widgets</exec_depend>

  <!-- Testing -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
